### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#16]
@timac11 @larioandr 

Просьба добавить новый раздел Venue на сайте DCCN-2022 во вкладке Conference.

Содержание раздела:

The DCCN-2022 conference will be held in a hybrid mode (with physical and virtual participation) in the premises of the RUDN University. 

Address: 
[RUDN University](http://eng.rudn.ru/), Building of Engineering and Science faculties,
115419, Moscow, Ordzhonikidze str. 3

[ View on Map](https://goo.gl/maps/AfW6KP6FZ3HqoiB96)

**Comment by timac11** [comment]
ok, will add it today
