### ISSUE TITLE
DCCN-2022: Conference schedule

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#18]
@timac11 

Просьба открыть раздел Conference Schedule из заполнить его аналогично тому, как это было в прошлом году (https://2021.dccn.ru/program). Сетку конференции в PDF и Excel прикрепляю. Контент секций пришлю позже отдельным issue.

[DCCN2022_program_overview.pdf](https://github.com/dccnconf/web22/files/9610517/DCCN2022_program_overview.pdf)

[DCCN2022_program_overview_v5.xlsx](https://github.com/dccnconf/web22/files/9610535/DCCN2022_program_overview_v5.xlsx)

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 

Просьба заменить PDF и внести правку в расписание на сайте. Теперь регистрация начинается не в 11.00, а в 12.00.

[DCCN2022_program_overview.pdf](https://github.com/dccnconf/web22/files/9626073/DCCN2022_program_overview.pdf)
