### ISSUE TITLE
DCCN-2022: Full conference program

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#20]
@timac11 

просьба разместить на сайте https://2022.dccn.ru/program полную программу конференции. 
В приоритете сначала разместить PDF файл.

[DCCN 2022 - Program_20220921.pdf](https://github.com/dccnconf/web22/files/9632468/DCCN.2022.-.Program_20220921.pdf)

**Comment by kozyrevdv** [comment]
@timac11 

Есть одна правка по программе на сайте. Из-за того, что не все авторы зарегились в uConfy, они не подтянулись в соавторы статьи 1746 на сайте. Просьба добавить их вручную. Правильный состав авторов:

(Секция B.1.1) 
Vidyottama Jain, Vladimir Vishnevsky, Dharmaraja Selvamuthu, Raina Raj
Analysis of Power Management in a Tethered High Altitude Platform using MAP/PH[3]/1 Retrial Queueing Model (ID 1746)

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 

Подъехали еще изменения в программе по просьбам докладчиков. Просьба:
1) в секции А.2.1. изменить имя E.Bogatyrev на  V.Bogatyrev.
1) перенести доклад Vladimir Bogatyrev, Anatoly Bogatyrev, Stanislav Bogatyrev 
Reliability of a redundant computer system, taking into account the features of restoring information of various criticality to loss (ID 1203) из секции B.1.2 в секцию А.2.1. в 12.15, сдвинув остальные 2 доклада в А.2.1. вниз.
2) перенести доклад Konstantin Vytovtov, Elizaveta Barabanova, Vladimir Vishnevsky
Modeling and analysis of the multi-channel queueing system transient behavior for piece-wise constant arrival rates (ID 1258) из B.1.1. в B.1.2. на 15.00 (вместо ID 1203)

**Comment by kozyrevdv** [comment]
@timac11 
PDF файл, соответственно, тоже необходимо заменить
[DCCN 2022 - Program_20220924.pdf](https://github.com/dccnconf/web22/files/9639033/DCCN.2022.-.Program_20220924.pdf)
