### ISSUE TITLE
DCCN-2022: замена PDF сборника

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#23]
@timac11 
Просьба заменить PDF-файл сборника трудов (https://2022.dccn.ru/downloads/DCCN-2022_proceedings.pdf) на обновленный:

 
[DCCN-2022_proceedings.pdf](https://github.com/dccnconf/web22/files/9704756/DCCN-2022_proceedings.pdf)

**Comment by timac11** [comment]
done
