### ISSUE TITLE
Springer proceedings: добавить CCIS сборник

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#29]
@timac11 
Просьба в разделе https://2022.dccn.ru/#proceedings **прошлогоднего** сайта дабавить реферальную ссылку и обложку вышедшего сборника CCIS 1748.

Обновленный текст раздела:
We are pleased to announce that both of the DCCN 2022 post-proceedings books (LNCS, volume 13766, and CCIS, volume 1748) have been published by Springer Nature. The books are available online.

[_этот кусок без изменений
обложка LNCS Volume cover
**LNCS 13766**
https://link.springer.com/book/10.1007/978-3-031-23207-7_
]

Обложка CCIS
![CCIS 1748 cover](https://user-images.githubusercontent.com/47321403/236537976-79c78f2f-64f6-4fcf-8ad1-0b5d87bd3b8c.png)

**CCIS 1748**
http://link.springer.com/openurl.asp?genre=issue&issn=1865-0929&volume=1748

**Comment by timac11** [comment]
done
