### ISSUE TITLE
Редактирование DNS-записей домена dccn.ru

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web22#7]
@larioandr 

Андрей, для того, чтобы письма, рассылаемые через Unisender, не попадали в спам, необходимо настроить аутентификацию домена dccn.ru. Для этого просьба добавить TXT-записи.

<html>
<body>

Имя домена/поддомена | Тип записи | Значение
-- | -- | --
@ | TXT | v=spf1 include:spf.unisender.com ~all
us._domainkey | TXT | v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4CPsqZ07j5SfWo7+KG/72Jozei6Dvg8sCUFYnN0uUyUx+uJVSzJAg5fj7wYVSLzshn6YAvbbEHHxnX5gu1ee/MNMhmeCjbW4ymp6PpmiU6lx2rJMqrF1JUpXqb8f8hWYTWrLsYGQku4uOObF15wZy4yYKUoy0aXRrAxtvpHZ1qQIDAQAB

</body>
</html>

Примечание от службы поддержки Unisender:
Иногда интерфейс управления DNS не позволяет использовать символ @ как имя домена/поддомена. В этом случае используйте имя вашего домена с точкой на конце, например: "dccn.ru."

**Comment by larioandr** [comment]
Добавил.
